#!/bin/bash

email=waiting.test@gmail.com
subject="Notification check on `date +'%Y-%m-%d %H:%M:%S'`"
echo $subject
echo "$subject" | mail -s "Notification check" $email

sleep 30
total=0

#var='10.1.30.121'
#target_file="/var/log/logstash/production/push_notifications_server/push_offline/`date +'%Y-%m-%d'`/`date +'%H'`/*"
#cmd="grep '$subject' $target_file"
#echo $cmd
#ret=`echo "$cmd" | ssh -o "StrictHostKeyChecking no" $var "bash -s"  | grep "$email" | grep "Send payload" | grep "resp: 200" | wc -l`
#echo $var $ret
#total=$(echo $total + $ret | bc) 

if [ $total -eq 0 ]
then
    for var in "$@"
    do
        cmd="tail -n100000 /var/log/easilydo/push_offline.log | fgrep '$subject' "
        echo $cmd
        ret=`echo "$cmd" | ssh -o "StrictHostKeyChecking no" $var "bash -s"  | grep "$email" | grep "Send payload" | grep "resp: 200" | wc -l`
        echo $var $ret
        total=$(echo $total + $ret | bc) 
        if [ $total -eq 0 ]
        then
            continue
        else
            break
        fi
    done
fi
echo $total

if [ $total -eq 0 ]
then
    echo "CRIT: Not found send notification for '$subject'"
    exit 2
else
    echo "OK: '$subject'"
    exit 0
fi