#!/bin/bash

email=waiting.test@gmail.com
subject="Notification check on `date +'%Y-%m-%d %H:%M:%S'`"
echo $subject
echo "$subject" | mail -s "Notification check" $email

sleep 20
total=0
for var in "$@"
do
    echo $var
    cmd="grep '$subject' /var/log/easilydo/push_offline.log"
    echo $cmd
    ret=`echo "$cmd" | ssh web_tools@$var -i /home/easilydo_deploy/.ssh/id_ras_web_tools "bash -s"  | grep "$email" | grep "Send payload" | grep "resp: 200" | wc -l`
    echo $ret
    total=$(echo $total + $ret | bc) 
done
echo $total

if [ $total -eq 0 ]
then
    echo "CRIT: Not found send notification for '$subject'"
    exit 2
else
    echo "OK: '$subject'"
    exit 0
fi